name: user_repository
description: "repo for handle users"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  path: ^1.8.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
